/**
 * Dutch public holidays (hoofdstuk 6.4.4).
 *
 * Easter drives every moving holiday, so it is computed once with the
 * Meeus/Jones/Butcher algorithm and the rest are offsets from it.
 */
import { addDays, toIsoDate, isoWeekday, type IsoDate } from '@showroom/shared';

export type HolidayName =
  | 'Nieuwjaarsdag'
  | 'Goede Vrijdag'
  | 'Eerste Paasdag'
  | 'Tweede Paasdag'
  | 'Koningsdag'
  | 'Bevrijdingsdag'
  | 'Hemelvaartsdag'
  | 'Eerste Pinksterdag'
  | 'Tweede Pinksterdag'
  | 'Eerste Kerstdag'
  | 'Tweede Kerstdag';

export type GeneratedHoliday = {
  name: HolidayName;
  date: IsoDate;
  /** Whether the office is closed. Every generated day can be toggled later. */
  isDayOff: boolean;
  year: number;
  autoGenerated: true;
};

export type HolidayOptions = {
  /** Good Friday is not a statutory day off for most employers. Default off. */
  includeGoodFriday: boolean;
  /** Whether Liberation Day counts as a day off at all. Default off. */
  includeLiberationDay: boolean;
  /**
   * Many CAOs grant Liberation Day only every five years. When true, the day is
   * only marked as a day off in lustrum years (2020, 2025, 2030, ...).
   */
  liberationDayOnlyInLustrumYears: boolean;
};

export const DEFAULT_HOLIDAY_OPTIONS: HolidayOptions = {
  includeGoodFriday: false,
  includeLiberationDay: false,
  liberationDayOnlyInLustrumYears: true,
};

/**
 * Easter Sunday for a Gregorian year, per Meeus/Jones/Butcher.
 * Returns a UTC midnight Date.
 */
export function easterSunday(year: number): Date {
  const a = year % 19;
  const b = Math.floor(year / 100);
  const c = year % 100;
  const d = Math.floor(b / 4);
  const e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4);
  const k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31); // 3 = March, 4 = April
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return new Date(Date.UTC(year, month - 1, day));
}

/**
 * Koningsdag: 27 April, moved to 26 April when 27 April is a Sunday.
 * (The King's birthday is never celebrated on a Sunday.)
 */
export function koningsdag(year: number): Date {
  const april27 = new Date(Date.UTC(year, 3, 27));
  return isoWeekday(april27) === 7 ? addDays(april27, -1) : april27;
}

/** True for years divisible by five, when Bevrijdingsdag is a lustrum year. */
export function isLustrumYear(year: number): boolean {
  return year % 5 === 0;
}

/** All Dutch public holidays for a calendar year, in date order. */
export function generateHolidays(
  year: number,
  options: Partial<HolidayOptions> = {},
): GeneratedHoliday[] {
  const opts: HolidayOptions = { ...DEFAULT_HOLIDAY_OPTIONS, ...options };
  const easter = easterSunday(year);

  const liberationIsDayOff =
    opts.includeLiberationDay &&
    (!opts.liberationDayOnlyInLustrumYears || isLustrumYear(year));

  const entries: Array<{ name: HolidayName; date: Date; isDayOff: boolean }> = [
    { name: 'Nieuwjaarsdag', date: new Date(Date.UTC(year, 0, 1)), isDayOff: true },
    { name: 'Goede Vrijdag', date: addDays(easter, -2), isDayOff: opts.includeGoodFriday },
    { name: 'Eerste Paasdag', date: easter, isDayOff: true },
    { name: 'Tweede Paasdag', date: addDays(easter, 1), isDayOff: true },
    { name: 'Koningsdag', date: koningsdag(year), isDayOff: true },
    { name: 'Bevrijdingsdag', date: new Date(Date.UTC(year, 4, 5)), isDayOff: liberationIsDayOff },
    { name: 'Hemelvaartsdag', date: addDays(easter, 39), isDayOff: true },
    { name: 'Eerste Pinksterdag', date: addDays(easter, 49), isDayOff: true },
    { name: 'Tweede Pinksterdag', date: addDays(easter, 50), isDayOff: true },
    { name: 'Eerste Kerstdag', date: new Date(Date.UTC(year, 11, 25)), isDayOff: true },
    { name: 'Tweede Kerstdag', date: new Date(Date.UTC(year, 11, 26)), isDayOff: true },
  ];

  return entries
    .sort((a, b) => a.date.getTime() - b.date.getTime())
    .map((entry) => ({
      name: entry.name,
      date: toIsoDate(entry.date),
      isDayOff: entry.isDayOff,
      year,
      autoGenerated: true as const,
    }));
}
